[build]
  command = "npm run build"
  publish = "storybook-static"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/iframe.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "*.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 